# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.IntegerField(),
        ),
    ]
